### ISSUE TITLE
the latest version of the code

### ISSUE THREAD

**Issue by Ako-r** [henrikmarklund/arm#10]
I'm sorry to disturb you. If it is convenient for you, can you update the latest version of the code?

**Comment by henrikmarklund** [comment]
Thank you for the interest :) Just pushed the code to branch release_2021 and made that the default branch!

**Comment by henrikmarklund** [comment]
Please let me know if you have any questions!

**Comment by Ako-r** [comment]
Thank you very much for your answer！

**Comment by Ako-r** [comment]
Hello, I am still confused that why you extend your framework on contextual meta-learning rather than previous work such as "Learning to generalize: Meta-learning for domain generalization".  Does the latter conflict with ARM framework? 
Thank you!

**Comment by zhangmarvin** [comment]
Previous work on meta-learning for domain generalization approaches the problem by meta-training models for out-of-domain generalization, i.e., the models do not adapt to the test domain. Our work, though also focusing on meta-learning and domain generalization, meta-trains models such that they can effectively adapt to the new test domain. That is why extending frameworks such as contextual meta-learning is a better fit.
