### ISSUE TITLE
some problem with the context c

### ISSUE THREAD

**Issue by Now-wuua** [henrikmarklund/arm#14]
What an excellent job! 
But I still have some problems with the context c. 
1. In this work, you take advantage of the context network to extract the conditional distribution p_{y|x} from the input data and use the conditional distribution to guide the prediction network. Is this right? If not, can you answer for me what context c specifically refers to？
2. What is the role of context c in prediction networks?
These questions have bothered me for a long time. If you are willing, I hope you can answer it for me.
Thank you! I will look forward to your reply very much！

**Comment by henrikmarklund** [comment]
Hi! Thank you for writing to me. I am so sorry for my late reply on this. I don’t think I would say that c represents p(y|x) if you take x to mean one input sample. Rather, the purpose of c is to encode information about the group from which x is drawn, which will inform the estimation of p(y|x). This information can be useful for the prediction network when making its prediction. For instance, this could be true when the input is ambiguous but for the knowledge of what group it belongs to (e.g., if you learn that all images in a batch are rotates 180 degrees, it’ll be easier to classify 6s and 9s).

I am happy to chat further about this and give more intuition. If so, perhaps you could send me an email. My email is my last name @stanford.edu.
