### ISSUE TITLE
How to reproduce the streaming experiment?

### ISSUE THREAD

**Issue by jyhong836** [henrikmarklund/arm#18]
Hi, thanks for sharing the codes.
I checked the codes but did not find the codes or instructions for reproducing the results of the streaming setting. Did I miss something? Or will you provide instruction on reproducibility in the future?

**Comment by henrikmarklund** [comment]
Hi :) Great to hear from you! We have not uploaded that at this moment, unfortunately. Feel free to send me an email if you want further guidance :)

**Comment by jyhong836** [comment]
I tried to run the streaming experiment by the following command
```
# non-streaming
python run.py --eval_on test --test 1 --train 0 --ckpt_folders mnistarm_bn_0_20220601-190129/ --log_wandb=False --adapt_bn=1
# streaming
python run.py --eval_on test --test 1 --train 0 --ckpt_folders mnistarm_bn_0_20220601-190129/ --log_wandb=False --support_size=1 --adapt_bn=1
```
where I suppose the `support_size=1` should be input one sample at one time. But it turns out the streaming (the 2nd run) performs much poorer than the first one. The former yields 95% avg ACC and the latter 12%. Are there any other parameters I should modify for the streaming setting?

**Comment by henrikmarklund** [comment]
Hey! Yeah, this isn't exactly correct but the spirit is right! The above won't update the c vector appropriately over time and will instead just be the same as having support size 1.

I sent you an email giving more details on what changes need to be made. I'll have more time on Sunday to give more hands-on guidance if that's not too late for you?
