### ISSUE TITLE
A question about  training batch sampling

### ISSUE THREAD

**Issue by kinredon** [henrikmarklund/arm#6]
I read the paper carefully, but I am still confused with the training batch sampling. Each batch images are sampled from a training group, but how do the authors **divide the training dataset into S groups with different distributions**?.

I hope the authors could note this issue and am looking forward to receiving your reply.

Thank you!

**Comment by henrikmarklund** [comment]
Hi! I am so sorry I missed your message earlier.

We assume that we are given the S groups in advance. In other words, for each example, we assume that we have some metadata, that tells us to which group the example belong.

Does that answer your question? Happy to elaborate!
